
import 'package:firebase_auth/firebase_auth.dart';

import 'package:cloud_firestore/cloud_firestore.dart';

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  
  Future<UserCredential> signUp({
    required String email,
    required String password,
  }) async {
    final userCredential = await _auth.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );

    final uid = userCredential.user!.uid; /*user credential is an object returned after a successful sign-in or sign-up and 
    it then it stores the uid generated by firebase for that user (which isnt null ofc)
     */
   
    await _firestore.collection('users').doc(uid).set({
      'email': email,
      'role': 'user', 
      'createdAt': FieldValue.serverTimestamp(), /*tells Firestore’s server to insert the current timestamp */
     
    });

    
    await userCredential.user!.sendEmailVerification();

    return userCredential;
  }

  
  Future<UserCredential> signIn({
    required String email,
    required String password,
  }) async {
    return await _auth.signInWithEmailAndPassword(
      email: email,
      password: password,
    );
  }

  
  Future<void> signOut() async {
    await _auth.signOut();
  }

  
  Future<void> resetPassword({required String email}) async {
    await _auth.sendPasswordResetEmail(email: email);
  }


  

  
  User? get currentUser => _auth.currentUser; /*to get the current user  */

  
  Stream<User?> get authStateChanges => _auth.authStateChanges();  /*to track the state changes  */
}
